server:
  port: 9001

spring:
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.100:8848
        username: nacos
        password: nacos
      config:
        server-addr: 192.168.0.100:8848
        username: nacos
        password: nacos
        file-extension: yaml
