server:
  port: 9001

spring:
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.100:8837,192.168.0.100:8848,192.168.0.100:8859
      config:
        server-addr: 192.168.0.100:8837,192.168.0.100:8848,192.168.0.100:8859
        file-extension: yaml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 12345678
  redis:
    host: 8.130.102.239
    port: 6379
    timeout: 10s
    lettuce:
      pool:
        max-active: 50
        max-idle: 50
        max-wait: -1ms
        min-idle: 0

third-party:
  gitee:
    clientId: 2ad120f48f602decb79bdc8c4cd29728e5aa80d598ccdfdc4c13495fdc1d68f6
    clientSecret: fd363b307c41eee9330ef3eca7ddf5d0e80349490ffc421b862b12ebaa378ed0
    call-back: http://localhost:9001/user/register/gitee
    token-url: https://gitee.com/oauth/token?grant_type=authorization_code&client_id=%s&client_secret=%s&redirect_uri=%s&code=%s
    user-url: https://gitee.com/api/v5/user?access_token=%s
    state: GITEE